// Generated by CoffeeScript 1.7.1
var h,
  __slice = [].slice;

h = require("./helpers");

module.exports = function() {
  var arg, args, cb, index, key, opts, _i, _len, _ref;
  args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
  _ref = h.splatParser.apply(h, args), args = _ref[0], opts = _ref[1], cb = _ref[2];
  if (opts != null) {
    args.push(opts);
  }
  for (index = _i = 0, _len = args.length; _i < _len; index = ++_i) {
    arg = args[index];
    if (index % 2 === 0) {
      key = arg;
    } else if (key != null) {
      config[key] = arg;
      key = null;
    }
  }
  return typeof cb === "function" ? cb() : void 0;
};
