// Generated by CoffeeScript 1.6.3
(function() {
  global.p = console.log;

  global.config = {};

  config.loadFilepath = require("./file");

  config.loadEnv = require("./env").loadEnv;

  config.getEnv = require("./env").getEnv;

  config.set = require("./set");

  config.etcd = require("./etcd");

  module.exports = global.config;

}).call(this);
